apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-conf
  namespace: default
spec:
  resources:
    requests:
    storage:  12Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn