---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  # - ./valkey-secret.yaml
  # - ./valkey-auth.yaml
  # - ./pvc-valkey.yaml
configMapGenerator:
  - name: valkey-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
