---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ghostfolio-redis-secret.yaml
  - ./ghostfolio-app-secret.yaml
  - ./ghostfolio-auth.yaml
  - ./pvc-ghost.yaml
configMapGenerator:
  - name: ghostfolio-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
