---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./test-christmas-secret.yaml
  - ./test-christmas-auth.yaml
  - ./pvc-santa.yaml
configMapGenerator:
  - name: test-christmas-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
