---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./automate-wx/ks.yaml
  - ./endlessh/ks.yaml
  - ./authentik/ks.yaml
  - ./hajimari/ks.yaml
  - ./redis/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./filebrowser/ks.yaml
  - ./jellyfin/ks.yaml
  - ./mealie/ks.yaml
  - ./kavita/ks.yaml
  - ./books/ks.yaml
  - ./livres/ks.yaml
  - ./immich/ks.yaml
  # - ./christmas/ks.yaml
  - ./testChristmas/ks.yaml
  - ./ghostfolio/ks.yaml
  - ./paperless-ngx/ks.yaml
  # - ./zitadel/ks.yaml
  # - ./qbittorrent/ks.yaml
  # - ./kubotheque/ks.yaml
  # - ./rabbitmq/ks.yaml
  - ./onlyoffice/ks.yaml