---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./paperless-redis-secret.yaml
  - ./paperless-db-secret.yaml
  - ./paperless-app-secret.yaml
  - ./paperless-auth.yaml
  - ./pvc-paperless-media.yaml
  - ./pvc-paperless-db.yaml
configMapGenerator:
  - name: paperless-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
