---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc-coder-conf.yaml
  - ./coder-auth.yaml
  - ./coder-app-secret.yaml
  - ./coder-db-secret.yaml
configMapGenerator:
  - name: coder-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
