apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
  namespace: default
spec:
  resources:
    requests:
      storage: 2048Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn