---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./cnpg-arr-secret.yaml
  - ./cnpg-auth-secret.yaml
  - ./cnpg-auth.yaml
  - ./cnpg-superuser-secret.yaml
  - ./cnpg-tand-secret.yaml
  - ./cnpg-vauban-secret.yaml
  - ./cnpg-mich-secret.yaml
  - ./cnpg-paper-secret.yaml
  - ./cnpg-office-secret.yaml
  - ./cnpg-chef-secret.yaml
  - ./db-tandoor.yaml
  - ./db-authentik.yaml
  - ./db-prowlarr-log.yaml
  - ./db-prowlarr-main.yaml
  - ./db-radarr-log.yaml
  - ./db-radarr-main.yaml
  - ./db-sonarr-log.yaml
  - ./db-sonarr-main.yaml
  - ./db-zitadel.yaml
  - ./db-onlyoffice.yaml
  - ./db-paperless.yaml
  - ./db-immich.yaml
  - ./db-mealie.yaml
